version: '3.8'

services:
  llm_guard_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config/scanners.yml:/home/user/app/config/scanners.yml
