app:
  name: ${APP_NAME:LLM Guard API}
  log_level: ${LOG_LEVEL:INFO}
  log_json: ${LOG_JSON:true}
  scan_fail_fast: ${SCAN_FAIL_FAST:false}
  scan_prompt_timeout: ${SCAN_PROMPT_TIMEOUT:30}
  scan_output_timeout: ${SCAN_OUTPUT_TIMEOUT:30}
  lazy_load: ${LAZY_LOAD:true}

rate_limit:
  enabled: ${RATE_LIMIT_ENABLED:false}
  limit: ${RATE_LIMIT_LIMIT:100/minute}

auth:
 type: http_bearer
 token: ${AUTH_TOKEN:}

tracing:
  exporter: ${TRACING_EXPORTER:console}
  endpoint: ${TRACING_OTEL_ENDPOINT:}  # Example: "<traces-endpoint>/v1/traces"

metrics:
  exporter: ${METRICS_TYPE:prometheus}
  endpoint: ${METRICS_ENDPOINT:}  # Example: "<metrics-endpoint>/v1/metrics"

# Scanners are applied in the order they are listed here.
input_scanners:
  - type: BanTopics
    params:
      topics:
        - "violence"
        - "crime"
        - "terrorism"
        - "illegal_drugs"
        - "politics"
        - "religion"
        - "sexual_content"
        - "medical_advice"
        - "financial_predictions"
        - "economy"
        - "entertainment"
        - "discrimination"
        - "injustice"
      threshold: 0.75
      model_max_length: 512
  - type: PromptInjection
    params:
      threshold: 0.92
      match_type: truncate_head_tail
      model_max_length: 512
  - type: Toxicity
    params:
      threshold: 0.90
      model_max_length: 512


output_scanners:
  - type: BanCode
    params:
      threshold: 0.97
      model_max_length: 512
  - type: BanTopics
    params:
      topics:
        - "violence"
        - "crime"
        - "terrorism"
        - "illegal_drugs"
        - "politics"
        - "religion"
        - "sexual_content"
        - "medical_advice"
        - "financial_predictions"
        - "economy"
        - "entertainment"
        - "discrimination"
        - "injustice"
      threshold: 0.75
  - type: Gibberish
    params:
      threshold: 0.97
      model_max_length: 512
  - type: Toxicity
    params:
      threshold: 0.90
      model_max_length: 512
  - type: EmotionDetection
    params:
      threshold: 0.5
      blocked_emotions:
        - "anger"
        - "annoyance"
        - "disappointment"
        - "disapproval"
        - "disgust"
        - "embarrassment"
        - "fear"
        - "grief"
        - "nervousness"
        - "remorse"
        - "sadness"
      model_max_length: 512