app:
  name: ${APP_NAME:LLM Guard API}
  log_level: ${LOG_LEVEL:INFO}
  log_json: ${LOG_JSON:true}
  scan_fail_fast: ${SCAN_FAIL_FAST:false}
  scan_prompt_timeout: ${SCAN_PROMPT_TIMEOUT:30}
  scan_output_timeout: ${SCAN_OUTPUT_TIMEOUT:30}
  lazy_load: ${LAZY_LOAD:true}

rate_limit:
  enabled: ${RATE_LIMIT_ENABLED:false}
  limit: ${RATE_LIMIT_LIMIT:100/minute}

auth:
 type: http_bearer
 token: ${AUTH_TOKEN:}

tracing:
  exporter: ${TRACING_EXPORTER:console}
  endpoint: ${TRACING_OTEL_ENDPOINT:}  # Example: "<traces-endpoint>/v1/traces"

metrics:
  exporter: ${METRICS_TYPE:prometheus}
  endpoint: ${METRICS_ENDPOINT:}  # Example: "<metrics-endpoint>/v1/metrics"

# Scanners are applied in the order they are listed here.
input_scanners:
  - type: Anonymize
    params:
      use_faker: false
      threshold: 0.75
      # model_path: "./distilbert_finetuned_ai4privacy_v2"
  - type: BanCode
    params:
      threshold: 0.97
      model_max_length: 256
  - type: BanCompetitors
    params:
      competitors: ["facebook"]
      threshold: 0.75
  - type: BanSubstrings
    params:
      substrings: ["test"]
      match_type: "word"
      case_sensitive: false
      redact: false
      contains_all: false
  - type: BanTopics
    params:
      topics: ["violence"]
      threshold: 0.8
      model_max_length: 256
#  - type: Code
#    params:
#      languages: ["Python"]
#      is_blocked: true
  - type: Gibberish
    params:
      threshold: 0.97
      model_max_length: 256
  - type: InvisibleText
    params: { }
  - type: Language
    params:
      valid_languages: [ "en" ]
      model_max_length: 256
  - type: PromptInjection
    params:
      threshold: 0.92
      match_type: truncate_head_tail
      model_max_length: 256
  - type: Regex
    params:
      patterns: ["Bearer [A-Za-z0-9-._~+/]+"]
      is_blocked: true
      match_type: search
      redact: true
  - type: Secrets
    params:
      redact_mode: "all"
  - type: Sentiment
    params:
      threshold: 0.0
  - type: TokenLimit
    params:
      limit: 4096
      encoding_name: "cl100k_base"
  - type: Toxicity
    params:
      threshold: 0.9
      model_max_length: 256


output_scanners:
  - type: BanCode
    params:
      threshold: 0.97
      model_max_length: 256
  - type: BanCompetitors
    params:
      competitors: ["facebook"]
      threshold: 0.75
  - type: BanSubstrings
    params:
      substrings: ["test"]
      match_type: "word"
      case_sensitive: false
      redact: false
      contains_all: false
  - type: BanTopics
    params:
      topics: ["violence"]
      threshold: 0.8
  - type: Bias
    params:
      threshold: 0.97
      model_max_length: 256
#  - type: Code
#    params:
#      languages: ["Python"]
#      is_blocked: true
  - type: Deanonymize
    params:
      matching_strategy: "exact"
  - type: FactualConsistency
    params:
      minimum_score: 0.5
  - type: Gibberish
    params:
      threshold: 0.97
#  - type: JSON
#    params:
#      required_elements: 0
#      repair: true
  - type: Language
    params:
      valid_languages: [ "en" ]
      model_max_length: 256
  - type: LanguageSame
    params:
      model_max_length: 256
  - type: MaliciousURLs
    params:
      threshold: 0.75
  - type: NoRefusal
    params:
      threshold: 0.9
  - type: ReadingTime
    params:
      max_time: 5
      truncate: false
  - type: Regex
    params:
      patterns: ["Bearer [A-Za-z0-9-._~+/]+"]
      is_blocked: true
      match_type: search
      redact: true
  - type: Relevance
    params:
      threshold: 0.2
  - type: Sensitive
    params:
      redact: false
      threshold: 0.75
  - type: Sentiment
    params:
      threshold: 0.0
  - type: Toxicity
    params:
      threshold: 0.9
      model_max_length: 256
  - type: URLReachability
    params: {}
