name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    with:
      secrets: |
        "HF_TOKEN=${{ secrets.HF_TOKEN }}"

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd llm_guard_api && docker build . --file Dockerfile --tag guochengjie/llm-guard-api-offline-cn:$(date +%s) --tag guochengjie/llm-guard-api-offline-cn:latest

